audio_driver: 'pyaudio'
rate: 160000
bits: 16
chunksize: 1024
channel: 2

# likely in the format of 'tcp://127.0.0.1:YOUR_PORT_NUMBER'
publish_address: ''
subscribe_address: ''
audio_publish_address: ''
